#Amelia Hampford
#agh3ft
#Makefile PostLab10

CXX	= clang++
CXXFLAGS = -std=c++0x

OFILES = TreeCalc.o TreeCalcTest.o TreeNode.o
.SUFFIXES: .o .cpp

a.out: $(OFILES)
	$(CXX) $(DEBUG) $(OFILES)

clean:
	/bin/rm -f *.o *~
